# Logitech Attack3
axis_linear: 1  # Forward/Back
scale_linear: 5
scale_linear_turbo: 10

axis_angular: 0  # Left/Right
scale_angular: 10

enable_button: 0  # Trigger
enable_turbo_button: 1  # Button 2 aka thumb button
