axis_linear: 1  # Left thumb stick vertical
scale_linear: 5.0
scale_linear_turbo: 10.0

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 10

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
